# Generated by Django 6.1.1 on 2026-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('kind', models.CharField(choices=[('spent', 'Spent'), ('received', 'Received')], default='spent', max_length=20)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('date', models.CharField(db_index=True, max_length=20)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('reminder_id', models.CharField(blank=True, default='', max_length=100)),
                ('auto_logged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('budget', models.FloatField(default=0.0)),
                ('monthly_income', models.FloatField(default=0.0)),
                ('saving_goal', models.FloatField(blank=True, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(default='Other', max_length=50)),
                ('icon', models.CharField(default='✦', max_length=20)),
                ('created_on', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('friends', models.JSONField(default=list)),
                ('date', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
